### PR TITLE
cli: some improvements for password

### LINKED ISSUE #103: [BUG] --auto parameter
Maybe i missed something or what ,but....:

c:\Users\karbantartokac\Desktop\z>dex encrypt --auto 1.dat 1.enc
-960996e0m Your generated passphrase is: September
←[36mℹ←[0m Using XChaCha20-Poly1305 for encryption
←[36mℹ←[0m Encrypting 1.dat (this may take a while)
←[32m✔←[0m Successfully hashed your key [took 2.96s]
←[32m✔←[0m Encryption successful! File saved as 1.enc [took 0.60s]

c:\Users\karbantartokac\Desktop\z>dex decrypt 1.enc 1.kii
Password: September
←[36mℹ←[0m Using XChaCha20-Poly1305 for decryption
←[36mℹ←[0m Decrypting 1.enc (this may take a while)
←[32m✔←[0m Successfully hashed your key [took 2.85s]
Error: Unable to decrypt your master key (maybe you supplied the wrong key?)

Am i do something wrong ?!

### PR DESCRIPTION
**Pull request by pleshevskiy**
This will probably fix #103, but I can't check it.

### CODE REVIEW

File: dexios/src/subcommands/key.rs [hunk 1]
```diff
@@ -62,22 +62,13 @@ fn read_password_from_stdin_windows(prompt: &str) -> Result<String> {
 // if direct mode is enabled, it just reads the password once and returns it instantly
 pub fn get_password(pass_state: &PasswordState) -> Result<Protected<Vec<u8>>> {
     Ok(loop {
-        #[cfg(target_family = "unix")]
-        let input =
-            read_password_from_stdin_unix("Password: ").context("Unable to read password")?;
-        #[cfg(target_family = "windows")]
-        let input =
-            read_password_from_stdin_windows("Password: ").context("Unable to read password")?;
+        let input = read_password_from_stdin("Password: ").context("Unable to read password")?;
```
Comment (brxken128) [inline dexios/src/subcommands/key.rs:65]: I had no clue this could be determined dynamically, that's awesome!

**Comment by brxken128** [comment]
Nice work as usual my friend, thank you so much for all of these improvements!
